### ISSUE TITLE
Review the possibility of changing mc.png

### ISSUE THREAD

**Issue by eddieoz** [eddieoz/youtube-clips-automator#4]
Related to #2 from [jaonoctus](https://github.com/jaonoctus)

I could not modify the mc.png to other image.

```
marcelo    | Traceback (most recent call last):
marcelo    |   File "./thumb_generator.py", line 216, in <module>
marcelo    |     main(args.input, args.title, args.no_delete_thumbs)
marcelo    |   File "./thumb_generator.py", line 185, in main
marcelo    |     create_thumbnail(input, title, delete_thumbs)
marcelo    |   File "./thumb_generator.py", line 155, in create_thumbnail
marcelo    |     face = find_smile(frame,text, count)
marcelo    |   File "./thumb_generator.py", line 65, in find_smile
marcelo    |     add_background(resizeimg, text)
marcelo    |   File "./thumb_generator.py", line 96, in add_background
marcelo    |     newimg.paste(mclogo, (W-mclogo_width-5,5), mclogo)
marcelo    |   File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 1557, in paste
marcelo    |     self.im.paste(im, box, mask.im)
marcelo    | ValueError: bad transparency mask
```

**Comment by eddieoz** [comment]
@jaonoctus Please, share the file you are trying to replace.

I had this problem before and it was related to the format/size of the exported png file. I need to do some tests to understand what happened.

You can send it privately or share it encrypted :)

**Comment by jaonoctus** [comment]
I could not find you PGP key (`C2056B0C12D579A5B172AB853480FB98373B56FB`) containing a user id.

Here is the file:

![mc2](https://user-images.githubusercontent.com/7918067/167195147-37a6d864-5d13-4ab0-a52f-9321d457b9c9.png)

**Comment by eddieoz** [comment]
> 

@jaonoctus I solved both logo issues :)

About the public key, it is published here: https://keys.openpgp.org/search?q=C2056B0C12D579A5B172AB853480FB98373B56FB

Pls review the last 2 open issues, because maybe they are not bugs.

Best,
Edilson
