### ISSUE TITLE
Issue with list.csv

### ISSUE THREAD

**Issue by eddieoz** [eddieoz/youtube-clips-automator#6]
Related to #2 from @jaonoctus

I think that the format of the list.csv is outdated. Generated a thumbnail and the title there was "0" (from the podcast field).

**Comment by eddieoz** [comment]
@jaonoctus There's a chance of having an extra comma (,) on the list.csv file, which changes the order of the fields when the script is reading it.

Can you share the line of list.csv you are trying please? Because Marcelo edited a clip yesterday and I didn't change the format of the file.

**Comment by jaonoctus** [comment]
```csv
url,time_from,time_to,cut,podcast,title,description,tags
https://www.youtube.com/watch?v=at-EHIrtJHw,00:00:00,00:01:00,1,0,TESTE,TESTE,teste1 teste2
```

**Comment by eddieoz** [comment]
You were correct... the format is outdated.
```
url,time_from,time_to,podcast,title,description,tags
https://www.youtube.com/watch?v=at-EHIrtJHw,00:00:00,00:01:00,0,TESTE,TESTE,teste1 teste2
```
I uploaded the new list.csv, but forgot to update the sample.
